# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Santiago Robles
title: Estudiante de Licenciatura en Ciencias de la Computacion
email: gsrrobles@gmail.com
website: https://rovlezmex.github.io/

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  RovlezMex
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: Sobre mi
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hola, mi nombre es Gabriel Santiago Robles Robles, soy estudiante de la licenciatura en Ciencias de la Computacion, apasionado por la creacion de software que genere un impacto, la solucion de problemas y la creacion de soluciones creativas.

  Tengo habilidades fuertes en: <mark>Python</mark> and <mark>ML/AI</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Proyectos de Inteligencia Artificial
        link: https://github.com/RovleZMex/ML-and-AI-Projects
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Trabajos de aprendizaje supervisado y no supervisado.
        description: | # this will include new lines to allow paragraphs
          He hecho estos proyectos como parte de mis capacitaciones en <mark>ML</mark>. Estos poryectos me sirvieron como herramienta para aterrizar los conceptos que vimos en los cursos. 
  
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Universidad de Sonora
        caption: 2021 - Actual
        sub_title: Licenciatura en Ciencias de la Computacion
        description: | # this will include new lines to allow paragraphs
          Actualmente estoy en mi ultimo año de la licenciatura y estoy ansioso por poner en practica todo lo que he aprendido en mi etapa academica. Me he rodeado de muy buenos profesores y compañeros con los que me mantengo activamente participando en todo tipo de actividades. 
      - layout: left
        title: Carleton University
        caption: Mayo 2024 - Agosto 2024
        sub_title: Estancia de Investigacion
        quote: > 
          Ottawa, Canada
        description: |
          Trabaje con la Dra. Nadine Moacdieh en un proyecto de investigacion sobre el impacto del uso de HUDs en automoviles autonomos. Hice investigacion sobre literatura anterior, diseñe el experimento y realizamos experimentos con participantes humanos. Aprendi muchisimo sobre como trabajar en un ambiente internacional y tuve la oportunidad de medirme con estudiantes de las mejores universidades del mundo.
        
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
